install:
- sudo apt-get install texlive-publishers texlive-latex-recommended texlive-latex-extra
  texlive-fonts-recommended texlive-science texlive-generic-recommended
- sudo apt-get install latexmk
script:
- make
- make clean
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
