install:
- sudo apt-get install texlive-publishers texlive-latex-recommended texlive-latex-extra
  texlive-fonts-recommended texlive-science texlive-generic-recommended texlive-fonts-extra
- sudo apt-get install latexmk
script:
- cd LectureNotes
- make
- make clean
deploy:
  provider: pages
  #github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
