install:
- sudo apt-get install texlive-publishers texlive-latex-recommended texlive-latex-extra
  texlive-fonts-recommended texlive-science texlive-plain-generic
- sudo apt-get install latexmk
script:
- cd LectureNotes
- make
- make clean
env:
  global:
    secure: mH/G5IXTw+jhAAqvCytrzgG7yMWr91WpJ+Wti5MQbUazEEPrwFoj/nwFu2tbzBJYUjHa1Y/KrCqn9xe/Za8KQ0jWYGWYyq8DzN8qmwn/VHhWVi6GCzQSQy4LEjhU5DF0Lr919dyJUVyPdeiQEcpirekPrZ2BxGVuDr0eX9Pj8ILhq28xSvEP1OltRrbJQfBHQ5s2gUlb9rjOnODRlkSvW25wr3KbpO1z7GT/OgmgBvQcjZdX289g6g2Wu4JuaVKTkl5sFclWeLazGUriWfKf7fohvzH1RVa3oSSCzq3+QQH5dyhh7KLeeHR599pKIH4vhjI8gRW7zafdrEWlbmdiyrQHbhGCLgtotoKnkkrS/jN6ekLbNNkDb1iVZbNOWf9CMw3me/Ush096nARdjYGbC6vYR4t1F210hweAIUWT9NiYe2oG+gioy+wRHOFEfVxQ4mMXbyepYRzs9Ed5nqkDgfuA4z8kd/g7hvp0PJZXbOuXE7wNCgX6r/VeuFhSdsk9GPXRB4sLr2peLtPrx7oB3nAvS4LHvFZD7+Vong63Ifh8YmUSq29pyaiEjxO0VJQPgGnzwRi+JTxRuDiY3/iJUW/dUDFkAsSPcYx6PmIJCBZLzjxhAFcfXsPBugHmqXrYC2JFF7YJxorqBC7/3kAU0qGERW4wgcuqdghzouTNc7g=
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
